name:                enum-subset-generate
version:             0.1.0.0
github:              "0xd34df00d/enum-subset-generate"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2018 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Generate a type with a subset of constructors with the corresponding surjection and injection
category:            Data

description:         Please see the README on GitHub at <https://github.com/0xd34df00d/enum-subset-generate#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- extra

library:
  source-dirs: src

tests:
  enum-subset-generate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - enum-subset-generate
